---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: primary-pool
  namespace: metallb-system
  labels:
    environment: production
spec:
  addresses:
    - 192.168.21.200-192.168.21.210
  autoAssign: true
  avoidBuggyIPs: true

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - primary-pool
  interfaces:
    - eth0
    - ens160
    - ens192

---
