name: Deploy Kubernetes Cluster via Ansible

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted   
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory.ini k8s_cluster_creation.yaml